#+TITLE: GUI
#+OPTIONS: toc:nil num:nil ^:nil

* Basic GUI Settings
#+NAME: gui-basics
#+BEGIN_SRC emacs-lisp
;; show column number and line number
(dolist (mode '(column-number-mode line-number-mode))
  (when (fboundp mode) (funcall mode t)))

(dolist (mode-hook '(text-mode-hook prog-mode-hook))
  (add-hook mode-hook
            (lambda ()
              (linum-mode 1))))

;; make the fringe thinner (default is 8 in pixels)
(fringe-mode 4)

;; show parenthesis match
(show-paren-mode 1)
(setq show-paren-style 'expression)

;; Toggle line highlighting in all buffers
(global-hl-line-mode t)
#+END_SRC

* Choose Monaco as the Default English Font
  :PROPERTIES:
  :CUSTOM_ID: font
  :END:

See https://github.com/cstrap/monaco-font.

#+NAME: font
#+BEGIN_SRC emacs-lisp
;; frame font
;; Setting English Font
(if (member "Monaco" (font-family-list))
    (set-face-attribute
     'default nil :font "Monaco 14"))
#+END_SRC

* Full screen support
  :PROPERTIES:
  :CUSTOM_ID: fullscreen
  :END:

#+BEGIN_SRC emacs-lisp
;; http://www.emacswiki.org/emacs/FullScreen
(defun bmaas/toggle-fullscreen ()
  "Toggle full screen"
  (interactive)
  (set-frame-parameter
   nil 'fullscreen
   (when (not (frame-parameter nil 'fullscreen)) 'fullboth)))

;; (global-set-key (kbd "<f11>") 'bmaas/toggle-fullscreen)
#+END_SRC

* Powerline
  :PROPERTIES:
  :CUSTOM_ID: powerline
  :END:

Powerline is an eye candy for emacs [[http://www.gnu.org/software/emacs/manual/html_node/emacs/Mode-Line.html][mode line]]. Actually, the [[https://github.com/milkypostman/powerline][emacs powerline]] is
inspired by [[https://github.com/Lokaltog/vim-powerline][vim-powerline]]. There're also powerline variants for [[https://github.com/erikw/tmux-powerline][tmux]], [[https://github.com/milkbikis/powerline-shell][shell]], etc.

#+NAME: powerline
#+BEGIN_SRC emacs-lisp :tangle no
(defun bmaas/powerline-setup ()
  (powerline-default-theme))

(bmaas/install 'powerline 'bmaas/powerline-setup)
#+END_SRC

* Solarized Color Theme
  :PROPERTIES:
  :CUSTOM_ID: color-theme
  :END:

#+BEGIN_QUOTE
 Solarized is a sixteen color palette (eight monotones, eight accent colors)
 designed for use with terminal and gui applications. It has several unique
 properties. I designed this colorscheme with both precise CIELAB lightness
 relationships and a refined set of hues based on fixed color wheel
 relationships. It has been tested extensively in real world use on color
 calibrated displays (as well as uncalibrated/intentionally miscalibrated
 displays) and in a variety of lighting conditions.
#+END_QUOTE

#+NAME: color-theme
#+BEGIN_SRC emacs-lisp
(defun bmaas/solarized-theme-setup ()
  (load-theme 'solarized-dark t))

(bmaas/install 'solarized-theme 'bmaas/solarized-theme-setup)
#+END_SRC

* Yascroll
  :PROPERTIES:
  :CUSTOM_ID: yascroll
  :END:

[[https://github.com/m2ym/yascroll-el][yascroll.el]] is Yet Another Scroll Bar Mode for GNU Emacs.

#+NAME: yascroll
#+BEGIN_SRC emacs-lisp
(defun bmaas/yascroll-setup ()
  (global-yascroll-bar-mode 1))

(bmaas/install 'yascroll 'bmaas/yascroll-setup)
#+END_SRC

* Linum-relative
  :PROPERTIES:
  :CUSTOM_ID: linum-relative
  :END:

Nice relative linenumbers, after using it a while I prefer normal
line numbering.

#+NAME: linum-relative
#+BEGIN_SRC emacs-lisp
(defun bmaas/linum-relative-setup ()
  (require 'linum-relative)
  (linum-relative-toggle))

(bmaas/install 'linum-relative 'bmaas/linum-relative-setup)
#+END_SRC
